name: Metrics
on:
  # Roda a cada 24 horas (meia-noite)
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se você quiser testar agora
  workflow_dispatch:
  # Roda sempre que você der push na main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token secreto
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções visuais (Dark Mode)
          user: gabfarmarcondes
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin: Linguagens
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          
          # Plugin: Calendário Isométrico
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin: Seus Top Repositórios
          plugin_repositories: yes
          # Lista exata dos repositórios
          plugin_repositories_featured: Software-Project-BCC3004/backend, gabfarmarcondes/Movie_BD, gabfarmarcondes/Detectar-Burnout-via-EEG, gabfarmarcondes/EEG-MachineLearning-Kaggle
          
          # Configuração visual dos repositórios
          plugin_repositories_pinned: 0
          plugin_repositories_order: featured
          
          # Plugin: Gráfico de Estrelas
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
